language: node_js
node_js: stable
services:
- docker
addons:
  ssh_known_hosts: $host_ip
branches:
  only:
  - hexo
cache:
  directories:
    - node_modules
deploy:
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
  -in id_rsa.enc -out id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host $host_ip\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

install:
- npm install

script:
- npm run build
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t michaelgongm/$DOCKER_NAME:latest .
- docker push michaelgongm/$DOCKER_NAME:latest

after_success:
- ssh root@$host_ip -o StrictHostKeyChecking=no "cd ~;docker-compose pull $DOCKER_NAME;docker-compose
  stop $DOCKER_NAME;docker-compose rm -f $DOCKER_NAME;docker-compose up -d $DOCKER_NAME;exit"

notifications:
  email:
    - 1506301420@qq.com

