# Blog
keywords: Hexo,HTML,CSS,android,Linux
author: Author Name,name@example.com
description: Nothing lasts forever.
avatar: /images/favicon.png

# Social Accounts
twitter: 
rss: 
weibo: 
instagram: 
github: 
facebook: 

# Comment
duoshuo: 
disqus: 
gentie: 
